# Generated by Django 4.2.5 on 2024-12-05 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0006_employee_role"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={"verbose_name": "Employee", "verbose_name_plural": "Employees"},
        ),
    ]
