# Generated by Django 4.2.5 on 2024-12-05 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0007_alter_employee_options"),
    ]

    operations = [
        migrations.AlterModelOptions(name="employee", options={},),
    ]
