# Generated by Django 4.2.5 on 2024-12-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0008_alter_employee_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("token", models.CharField(blank=True, max_length=256, null=True)),
                ("token_expiry", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
