# Generated by Django 4.2.5 on 2024-12-05 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0009_user"),
    ]

    operations = [
        migrations.DeleteModel(name="User",),
    ]
